### ISSUE TITLE
在获取玩家信息时报错  `Bad key name (eof)`

### ISSUE THREAD

**Issue by MisaLiu** [MCDReforged/MinecraftDataAPI#9]
# 简要描述
今天在使用 [bot](https://github.com/MCDReforged/PluginCatalogue/blob/catalogue/plugins/bot/readme-zh_cn.md) 插件的 `!!bot spawn` 时服务器没有响应，查看控制台发现给出了如下信息：

```console
[Server] [16:48:54] [Server thread/INFO]: <HIMlaoS_Misa> !!bot spawn bot_test
[Server] [16:48:54] [Server thread/INFO]: HIMlaoS_Misa has the following entity data: {seenCredits: 1b, DeathTime: 0s, foodTickTimer: 0, recipeBook: {recipes: ["minecraft:blackstone_stairs_from_blackstone_stonecutting", "minecraft:pisto}
[MCDR] [16:48:54] [commandSpawn/ERROR] [minecraft_data_api]: [Minecraft Data API] Fail to Convert data "HIMlaoS_Misa has the following entity data: {seenCredits: 1b, De...": Bad key name (eof): line 1 column 33937 (char 33936)
[Server] [16:48:54] [Server thread/INFO]: HIMlaoS_Misa has the following entity data: "minecraft:overworld"
Exception in thread commandSpawn:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\mcdreforged\api\decorator\new_thread.py", line 29, in wrapped_target
    raise e from None
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\mcdreforged\api\decorator\new_thread.py", line 26, in wrapped_target
    self.__return_value = target(*args_, **kwargs_)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "plugins\Bot-v1.0.6.mcdr\bot\command_handler.py", line 455, in __command_spawn
  File "plugins\Bot-v1.0.6.mcdr\bot\bot_manager.py", line 174, in spawn
  File "plugins\Bot-v1.0.6.mcdr\bot\plugin.py", line 55, in get_location
TypeError: 'NoneType' object is not subscriptable
```

推测该报错是由 MinecraftDataAPI 造成的。

# 开启 `debug` 后的日志输出
[MCDR.log](https://github.com/MCDReforged/MinecraftDataAPI/files/12000143/MCDR.log)，删减了内容

# 环境信息
* 系统：Windows Server 2022 Datacenter
* Python：3.11.4
* MCDReforged：2.9.1
* hjson：3.1.0
* parse：1.19.1

### ~~吐槽~~
~~怎么昨天晚上还能用的今天就不行了~~

**Comment by Fallen-Breath** [comment]
MinecraftDataAPI 没有成功解析 `XpP: 1.0331472E-7f` 这个数据，得看看怎么支持

**Comment by Fallen-Breath** [comment]
Fixed in v1.5.0
